package opsis.views;

import opsis.controllers.GirisController;
import opsis.controllers.RandevuController;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import opsis.models.Kullanici;


/**
 *
 * @author Kıvanç
 */
public class GirisEkrani extends javax.swing.JFrame {
    public static String giristipi;
    boolean isLogin; //Login Flag'ı
    boolean isFromFocus; //Şifremi Unuttum Label'ı için bir flag.
    
    public GirisEkrani() {
        initComponents();
        GirisController girisController = new GirisController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giris_PNL = new javax.swing.JPanel();
        OPSIS_LBL = new javax.swing.JLabel();
        hata_LBL = new javax.swing.JLabel();
        kullaniciadi_LBL = new javax.swing.JLabel();
        kullaniciadi_TXT = new javax.swing.JTextField();
        sifre_LBL = new javax.swing.JLabel();
        sifre_TXT = new javax.swing.JPasswordField();
        giris_BTN = new javax.swing.JButton();
        sifremiunuttum_LBL = new javax.swing.JLabel();
        giristipi_CMB = new javax.swing.JComboBox<>();
        arka_plan_LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPSIS");
        setBackground(new java.awt.Color(0, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setForeground(java.awt.Color.white);
        setIconImages(null);
        setLocation(new java.awt.Point(500, 250));
        setMinimumSize(new java.awt.Dimension(300, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 450));

        giris_PNL.setBackground(new java.awt.Color(255, 255, 255));
        giris_PNL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        giris_PNL.setDoubleBuffered(false);
        giris_PNL.setFocusCycleRoot(true);
        giris_PNL.setFocusTraversalPolicyProvider(true);
        giris_PNL.setNextFocusableComponent(kullaniciadi_TXT);
        giris_PNL.setOpaque(false);
        giris_PNL.setPreferredSize(new java.awt.Dimension(350, 450));

        OPSIS_LBL.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        OPSIS_LBL.setForeground(new java.awt.Color(51, 51, 51));
        OPSIS_LBL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        OPSIS_LBL.setLabelFor(arka_plan_LBL);
        OPSIS_LBL.setText("OPSIS");
        OPSIS_LBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OPSIS_LBL.setNextFocusableComponent(kullaniciadi_TXT);

        hata_LBL.setBackground(new java.awt.Color(255, 255, 255));
        hata_LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hata_LBL.setForeground(new java.awt.Color(255, 0, 0));
        hata_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hata_LBL.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        hata_LBL.setFocusable(false);
        hata_LBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        kullaniciadi_LBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kullaniciadi_LBL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        kullaniciadi_LBL.setText("Kullanıcı Adı");

        kullaniciadi_TXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kullaniciadi_TXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        kullaniciadi_TXT.setToolTipText("Kullanıcı Adı");
        kullaniciadi_TXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kullaniciadi_TXT.setFocusTraversalPolicyProvider(true);
        kullaniciadi_TXT.setNextFocusableComponent(sifre_TXT);
        kullaniciadi_TXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kullaniciadi_TXTKeyPressed(evt);
            }
        });

        sifre_LBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sifre_LBL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        sifre_LBL.setLabelFor(sifre_TXT);
        sifre_LBL.setText("Şifre");
        sifre_LBL.setToolTipText("");

        sifre_TXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sifre_TXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sifre_TXT.setToolTipText("Şifre");
        sifre_TXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sifre_TXTKeyPressed(evt);
            }
        });

        giris_BTN.setBackground(new java.awt.Color(255, 255, 255));
        giris_BTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giris_BTN.setText("Giriş");
        giris_BTN.setToolTipText("Tamam");
        giris_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giris_BTN.setFocusTraversalPolicyProvider(true);
        giris_BTN.setNextFocusableComponent(sifremiunuttum_LBL);
        giris_BTN.setRolloverEnabled(false);

        sifremiunuttum_LBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sifremiunuttum_LBL.setText("Şifremi Unuttum");
        sifremiunuttum_LBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifremiunuttum_LBL.setNextFocusableComponent(kullaniciadi_TXT);
        sifremiunuttum_LBL.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sifremiunuttum_LBLMouseMoved(evt);
            }
        });
        sifremiunuttum_LBL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sifremiunuttum_LBLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sifremiunuttum_LBLFocusLost(evt);
            }
        });
        sifremiunuttum_LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifremiunuttum_LBLMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sifremiunuttum_LBLMouseExited(evt);
            }
        });
        sifremiunuttum_LBL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sifremiunuttum_LBLKeyPressed(evt);
            }
        });

        giristipi_CMB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giristipi_CMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doktor", "Sekreter", "Yönetici" }));
        giristipi_CMB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        giristipi_CMB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                giristipi_CMBMouseMoved(evt);
            }
        });

        org.jdesktop.layout.GroupLayout giris_PNLLayout = new org.jdesktop.layout.GroupLayout(giris_PNL);
        giris_PNL.setLayout(giris_PNLLayout);
        giris_PNLLayout.setHorizontalGroup(
            giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, giris_PNLLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(OPSIS_LBL)
                .add(89, 89, 89))
            .add(giris_PNLLayout.createSequentialGroup()
                .add(19, 19, 19)
                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(hata_LBL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(giris_PNLLayout.createSequentialGroup()
                        .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(sifremiunuttum_LBL)
                            .add(giris_PNLLayout.createSequentialGroup()
                                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(sifre_LBL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(kullaniciadi_LBL))
                                .add(18, 18, 18)
                                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(giris_PNLLayout.createSequentialGroup()
                                        .add(giristipi_CMB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(giris_BTN))
                                    .add(kullaniciadi_TXT)
                                    .add(sifre_TXT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        giris_PNLLayout.setVerticalGroup(
            giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(giris_PNLLayout.createSequentialGroup()
                .add(74, 74, 74)
                .add(OPSIS_LBL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(66, 66, 66)
                .add(hata_LBL)
                .add(18, 18, 18)
                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(kullaniciadi_LBL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(kullaniciadi_TXT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sifre_TXT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sifre_LBL))
                .add(18, 18, 18)
                .add(giris_PNLLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(giristipi_CMB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(giris_BTN))
                .add(18, 18, 18)
                .add(sifremiunuttum_LBL)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        arka_plan_LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opsis/jpegler/modern-abstract-background_1048-1003.jpg"))); // NOI18N
        arka_plan_LBL.setFocusCycleRoot(true);
        arka_plan_LBL.setFocusTraversalPolicyProvider(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(giris_PNL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(arka_plan_LBL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(giris_PNL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, arka_plan_LBL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void kullaniciadi_TXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kullaniciadi_TXTKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            giris_BTN.doClick();
        }
    }//GEN-LAST:event_kullaniciadi_TXTKeyPressed

    private void sifre_TXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifre_TXTKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            giris_BTN.doClick();
        }
    }//GEN-LAST:event_sifre_TXTKeyPressed

    private void sifremiunuttum_LBLMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLMouseMoved
        sifremiunuttum_LBL.setFont(new Font("Segoe UI", Font.BOLD, 14));
    }//GEN-LAST:event_sifremiunuttum_LBLMouseMoved

    private void sifremiunuttum_LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLMouseClicked
        if(SwingUtilities.isLeftMouseButton(evt)) {
            SifremiUnuttumEkrani sifremiUnuttumEkrani = new SifremiUnuttumEkrani();
            sifremiUnuttumEkrani.setVisible(true);
        }
    }//GEN-LAST:event_sifremiunuttum_LBLMouseClicked

    private void sifremiunuttum_LBLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLMouseExited
        if(!isFromFocus) {
            sifremiunuttum_LBL.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_sifremiunuttum_LBLMouseExited

    private void sifremiunuttum_LBLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLFocusGained
        sifremiunuttum_LBL.setFont(new Font("Segoe UI", Font.BOLD, 14));
        isFromFocus=true;
        
    }//GEN-LAST:event_sifremiunuttum_LBLFocusGained

    private void sifremiunuttum_LBLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLFocusLost
        sifremiunuttum_LBL.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        isFromFocus=false;
    }//GEN-LAST:event_sifremiunuttum_LBLFocusLost

    private void sifremiunuttum_LBLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifremiunuttum_LBLKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            SifremiUnuttumEkrani sifremiUnuttumEkrani = new SifremiUnuttumEkrani();
            sifremiUnuttumEkrani.setVisible(true);}
    }//GEN-LAST:event_sifremiunuttum_LBLKeyPressed

    private void giristipi_CMBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giristipi_CMBMouseMoved
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_giristipi_CMBMouseMoved

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OPSIS_LBL;
    private javax.swing.JLabel arka_plan_LBL;
    private javax.swing.JButton giris_BTN;
    private javax.swing.JPanel giris_PNL;
    private javax.swing.JComboBox<String> giristipi_CMB;
    private javax.swing.JLabel hata_LBL;
    private javax.swing.JLabel kullaniciadi_LBL;
    private javax.swing.JTextField kullaniciadi_TXT;
    private javax.swing.JLabel sifre_LBL;
    private javax.swing.JPasswordField sifre_TXT;
    private javax.swing.JLabel sifremiunuttum_LBL;
    // End of variables declaration//GEN-END:variables

    public JButton getGiris_BTN() {
        return giris_BTN;
    }

    public JLabel getHata_LBL() {
        return hata_LBL;
    }

    public JTextField getKullaniciadi_TXT() {
        return kullaniciadi_TXT;
    }

    public JPasswordField getSifre_TXT() {
        return sifre_TXT;
    }

    public JComboBox<String> getGiristipi_CMB() {
        return giristipi_CMB;
    }

    public JLabel getSifremiunuttum_LBL() {
        return sifremiunuttum_LBL;
    }
   
}
